---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
- name: ci-tasks
- name: release-repo

params:
  RELEASE_NAME:

outputs:
- name: release-tarball
- name: version

run:
  path: ci-tasks/runtime-config/tasks/bosh-create-release.sh
