---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
- name: ci-tasks

params:
  BOSH_USERNAME:
  BOSH_PASSWORD:
  BOSH_TARGET:

run:
  path: ci-tasks/scripts/bosh-cleanup.sh
