---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
- name: ci-tasks
- name: git-bits-service-release
- name: bits-service

outputs:
- name: bumped

run:
  path: ci-tasks/scripts/bump-release.sh
