---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
- name: ci-tasks
- name: git-repo
- name: git-sub-repo

outputs:
- name: bumped

params:
  SUB_MODULE_PATH: unconfigured

run:
  path: ci-tasks/scripts/bump-release.sh
