---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
- name: ci-tasks
- name: state

params:
- REPO_DIR: state-out
- FILENAME: metrics.csv
- COMMIT_MESSAGE: "Update metrics"

outputs:
- name: state-out

run:
  path: ci-tasks/scripts/commit-metrics.sh
