---
platform: linux

image: docker:///flintstonecf/ci

inputs:
  - name: cf-release-version
  - name: ci-tasks
  - name: git-cf-release

params:
  VERSION_FILE:

outputs:
- name: releases

run:
  path: ci-tasks/scripts/create-cf-release.sh
