---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
- name: ci-tasks
- name: bits-service-release
- name: bits-service-release-version

params:
  VERSION_FILE:
  RELEASE_VERSION_SUFFIX:

outputs:
- name: releases

run:
  path: ci-tasks/scripts/create-bits-release.sh
