---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
  - name: ci-tasks
  - name: capi-release

outputs:
  - name: releases
  - name: capi-release-version

params:
  VERSION_FILE:

run:
  path: ci-tasks/scripts/create-capi-release.sh
