---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
  - name: git-bits-service-ci

params:
  MESSAGE:

run:
  path: git-bits-service-ci/scripts/echo.sh
