---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: flintstonecf/ci

inputs:
- name: bits-service-release
- name: ci-tasks

outputs:
- name: docker-parts

run:
  path: ci-tasks/tasks/get-image-artifacts.sh
