---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
  - name: git_repo
  - name: ci-tasks

outputs:
  - name: patched_repo

params:
  SUBMODULE: not-configured
  PATCH_URL: not-configured

run:
  path: ci-tasks/scripts/git-apply-patch-to-submodule.sh
