---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
- name: a
- name: b
- name: ci-tasks

outputs:
  - name: merged

run:
  path: ci-tasks/scripts/merge-resources.sh
