---
platform: linux

image: docker:///flintstonecf/ci

inputs:
- name: git-bits-service-ci
- name: git-bits-service-ci-events

params:
  DEPLOYMENT_NAME:

run:
  path: git-bits-service-ci/scripts/publish-deployment-deleted.sh
