---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
- name: ci-tasks
- name: cf-release-tarball
- name: bits-service-release-tarball

params:
  RELEASE_TARBALL_DIRS:

run:
  path: ci-tasks/scripts/publish-release-tarball-urls.sh
