---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
  - name: ci-tasks

params:
  SSH_CONNECTION_STRING:
  SSH_KEY:
  BOSH_USERNAME:
  BOSH_PASSWORD:
  BOSH_DIRECTOR_IP:
  VAGRANT_GATEWAY:

run:
  path: ci-tasks/scripts/recreate-bosh-lite.sh
