---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
  - name: ci-tasks
  - name: deployment-vars
  - name: cf-smoke-tests

params:
  ENVIRONMENT_NAME: unconfigured
  CF_SYSTEM_DOMAIN:
  DEPLOYMENT_NAME: unconfigured

run:
  path: ci-tasks/scripts/run-smoke-tests.sh
