---
platform: linux

image: docker:///flintstonecf/ci

inputs:
- name: bits-service-system-test-source
- name: ci-tasks

params:
  BOSH_USERNAME:
  BOSH_PASSWORD:
  BOSH_TARGET:
  RELEASE_NAME:
  BITS_SERVICE_PRIVATE_ENDPOINT_IP:

run:
  path: ci-tasks/scripts/run-release-tests.sh
