---
platform: linux

image: docker:///flintstonecf/ci

inputs:
- name: git-bits-service-release
- name: git-bits-service-ci

params:
  BOSH_USERNAME:
  BOSH_PASSWORD:
  BOSH_TARGET:
  BITS_SERVICE_ENDPOINT:
  DEPLOYMENT_NAME:

run:
  path: git-bits-service-ci/scripts/run-release-tests.sh
