---
platform: linux


image_resource:
  type: docker-image
  source: { repository: flintstonecf/ci }

inputs:
- name: bitsgo
- name: ci-tasks

run:
  path: ci-tasks/scripts/run-bitsgo-unit-tests.sh

caches:
- path: .glide
