---
platform: linux


image_resource:
  type: docker-image
  source: { repository: flintstonecf/ci }

inputs:
- name: bitsgo
- name: ci-tasks

params:
 INTEGRATION_TEST_SETUP: undefined
 BLOBSTORE_TYPE: undefined

run:
  path: ci-tasks/tasks/run-bitsgo-contract-integration-tests.sh
