---
platform: linux

image: "docker:///cloudfoundry/capi#ruby-units"

inputs:
- name: git-cloud-controller
- name: git-bits-service-ci

run:
  path: git-bits-service-ci/scripts/run-cc-tests.sh

params:
  DB: mysql
  DB_CONNECTION_STRING: "mysql2://root:password@localhost:3306/cc_test"
