---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
  - name: ci-tasks

params:
  BOSH_TARGET:
  BOSH_USERNAME:
  BOSH_PASSWORD:
  ERRAND_NAME:
  DEPLOYMENT_NAME:

run:
  path: ci-tasks/scripts/run-errand.sh
