---
platform: linux

image: docker:///flintstonecf/ci

inputs:
- name: bits-service
- name: ci-tasks

params:
  BITS_CONFIG_FILE: spec/fixtures/sample_config.yml

run:
  path: ci-tasks/scripts/run-service-tests.sh
