---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
- name: ci-tasks
- name: acceptance-tests
- name: deployment-vars

outputs:

params:
  BOSH_TARGET:
  DEPLOYMENT_NAME:
  ENVIRONMENT_NAME:
  CF_DOMAIN: bosh-lite.com
  CF_DIAL_TIMEOUT: 300
  NODES: 12
  BITS_SERVICE_ENABLEMENT: with-bits-service-unknown

run:
  path: ci-tasks/scripts/run-cats.sh
