---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
- name: bits-service-system-test-source
- name: ci-tasks
- name: deployment-vars

params:
  BOSH_USERNAME: unconfigured
  BOSH_PASSWORD: unconfigured
  BOSH_TARGET: unconfigured
  RELEASE_NAME: unconfigured
  BITS_SERVICE_PRIVATE_ENDPOINT_IP: unconfigured
  DEPLOYMENT_NAME: unconfigured
  ENVIRONMENT_NAME: unconfigured
  DIRECTOR_NAME: unconfigured
  DIRECTOR_IP: unconfigured
  VARS_YAML:

run:
  path: ci-tasks/scripts/run-release-tests.sh
