---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
- name: bits-service-system-test-source
- name: ci-tasks
- name: vars-store

params:
  ENVIRONMENT_NAME: unconfigured
  DEPLOYMENT_NAME: unconfigured
  CF_DOMAIN: unconfigured
  HOSTS_ENTRY_FILE: unconfigured
  VARS_STORE_FILE: unconfigured

run:
  path: ci-tasks/scripts/run-system-tests.sh
