---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
- name: bits-service-system-test-source
- name: ci-tasks
- name: deployment-vars

params:
  BOSH_USERNAME:
  BOSH_PASSWORD:
  BOSH_TARGET:
  RELEASE_NAME:
  BITS_SERVICE_PRIVATE_ENDPOINT_IP:

run:
  path: ci-tasks/scripts/run-release-tests.sh
