---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
- name: bits-service-release
- name: ci
- name: vars-store

params:
  ENVIRONMENT_NAME:

run:
  path: ci/tasks/run-cc-updater-tests.sh
