---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
- name: ci-tasks
- name: bits-service-release
- name: deployment-vars

params:
  CF_DOMAIN: unconfigured
  test_suite: unconfigured
  ENVIRONMENT_NAME: unconfigured
  BSMT_PERSISTENT_ORG: unconfigured
  BSMT_PERSISTENT_SPACE: unconfigured
  noColorFlag:
  verbose:
  DEBUG:

run:
  path: ci-tasks/scripts/run-bits-service-migration-tests.sh
