---
platform: linux

image: docker:///flintstonecf/ci

inputs:
- name: bits-service-system-test-source
- name: ci-tasks

params:
  BOSH_USERNAME:
  BOSH_PASSWORD:
  BOSH_TARGET:
  BITS_SERVICE_ENDPOINT:
  DEPLOYMENT_NAME:

run:
  path: ci-tasks/scripts/run-release-tests.sh
