---
platform: linux

image: docker:///flintstonecf/ci

inputs:
  - name: ci-tasks

params:
  ACCEPTANCE_IP:
  SSH_KEY:
  FILE:
  VERSION_FILE:
  RELEASE_NAME:

run:
  path: ci-tasks/scripts/scp-to-acceptance.sh
