---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
- name: ci-tasks
- name: fork-repo
- name: upstream-repo

outputs:
- name: synced-repo

params:
  BRANCH: master

run:
  path: ci-tasks/scripts/sync-repo.sh
