---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
- name: ci-tasks
- name: manifests

outputs:

params:
  BOSH_TARGET:
  BOSH_USERNAME:
  BOSH_PASSWORD:
  MANIFEST:

run:
  path: ci-tasks/scripts/update-cloud-config.sh
