---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
- name: ci-tasks
- name: deployment-vars

params:
  DYNU_CLIENT_ID: unconfigured
  DYNU_SECRET: unconfigured
  SYSTEM_DOMAIN: unconfigured
  ENVIRONMENT_NAME: unconfigured

run:
  path: ci-tasks/scripts/update-dynu-dns-with-bosh-lite-ip.sh
