---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
  - name: git-bits-service-ci
  - name: releases

params:
  BOSH_TARGET:
  BOSH_USERNAME:
  BOSH_PASSWORD:
  RELEASE_FILE:

run:
  path: git-bits-service-ci/scripts/upload-release.sh
