---
platform: linux

image: docker:///flintstonecf/ci

inputs:
- name: git-bits-service

params:
  SSH_CONNECTION_STRING:
  SSH_KEY:
  BOSH_USERNAME:
  BOSH_PASSWORD:
  BOSH_DIRECTOR_IP:
  VAGRANT_GATEWAY:
  DIEGO_RELEASE_VERSION:
  ETCD_RELEASE_VERSION:
  GARDEN_LINUX_RELEASE_VERSION:
  CFLINUXFS2_ROOTFS_RELEASE_VERSION:

run:
  path: git-bits-service/ci/scripts/recreate-bosh-lite.sh
