---
platform: linux

image: docker:///flintstonecf/ci

inputs:
- name: git-bits-service

params:
  BITS_CONFIG_FILE: spec/fixtures/sample_config.yml

run:
  path: git-bits-service/ci/scripts/run-tests.sh
