---
platform: linux

image: docker:///flintstonecf/ci

inputs:
  - name: git-bits-service-release

params:
  OPENSTACK_AUTH_URL:
  OPENSTACK_USER_NAME:
  OPENSTACK_API_KEY:
  FILE_GLOB:
  REMOTE_FOLDER:

run:
  path: git-bits-service-release/ci/scripts/upload-to-object-storage.rb
