- type: replace
  path: /properties?/bits-service/buildpacks/webdav_config/ca_cert
  value: ((blobstore_ssl.ca))
- type: replace
  path: /properties?/bits-service/droplets/webdav_config/ca_cert
  value: ((blobstore_ssl.ca))
- type: replace
  path: /properties?/bits-service/packages/webdav_config/ca_cert
  value: ((blobstore_ssl.ca))
- type: replace
  path: /properties?/bits-service/app_stash/webdav_config/ca_cert
  value: ((blobstore_ssl.ca))
- type: replace
  path: /properties?/blobstore/tls
  value:
    cert: ((blobstore_ssl.certificate))
    private_key: ((blobstore_ssl.private_key))
    ca_cert: ((blobstore_ssl.ca))

- type: replace
  path: /variables?/name=blobstore_ssl
  value:
    name: blobstore_ssl
    type: certificate
    options:
      common_name: not_configured
      alternative_names:
      - blobstore.10.175.96.245.nip.io
      - '*.10.175.96.245.nip.io'
      - 10.175.96.245.nip.io
      ca: default_ca

- type: replace
  path: /variables?/name=default_ca
  value:
    name: default_ca
    options:
      common_name: ca
      is_ca: true
    type: certificate
