networks:
- name: cf_private
  type: manual
  subnets:
  - range: 10.0.32.0/20
    gateway: 10.0.32.1
    dns: [10.0.0.2]
    reserved: ["10.0.32.2 - 10.0.32.3"]
    static: ["10.0.32.100 - 10.0.32.105"]
    cloud_properties:
      subnet: subnet-866839e2

- name: cf_public
  type: manual
  subnets:
  - range: 10.0.80.0/20
    gateway: 10.0.80.1
    dns: [10.0.0.2]
    reserved: ["10.0.80.2 - 10.0.80.10"]
    cloud_properties:
      subnet: subnet-bd9fced9
      security_groups:
        - sg-2813af4e
