- type: replace
  path: /properties/consul/encrypt_keys/0
  value: Atzo3VBv+YVDzQAzlQRPRA==
- type: replace
  path: /properties/consul/ca_cert
  value: |+
    -----BEGIN CERTIFICATE-----
    MIIE5jCCAs6gAwIBAgIBATANBgkqhkiG9w0BAQsFADATMREwDwYDVQQDEwhjb25z
    dWxDQTAeFw0xNzA4MDgxMzA4MTlaFw0yNzA4MDgxMzA4MjNaMBMxETAPBgNVBAMT
    CGNvbnN1bENBMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAuAxHwqrb
    WJjjRcHm2mxuMZGxSnPXzjXWyjLlmjN4sgE9bjKwaZGVmtsHpT7yA1eynmrnSv0n
    Nh4btM4exmMptMp8CbFuL5SDGpxHWflbDOMnbFLH6wDYmCaT42DtMVQdJtYHvnL6
    87HC2P11Hm5unb/SW3y78EbpsrweYb4suumPA9MRaDOIFOv6KL+TsJm7U8wEDS9F
    cAMjzYV1pEC+JTGVWbKwTEL20NAdr7rXwglMfT4nAa3Wgl1b80w94PSniLQnGlz/
    ZtsoAvZ0j0h1c8JlO7cMfbGK+v6VzVAx63ZACmAMr+l6y4D6TL32daF/tdsEx2kZ
    QWH0j8xBTfzw0PfE9fl+c3tc1QWAabyk9G9c62w/tiEjf4G8oEjzhAWm+NhjywOB
    JyjXIGuwYoCpOVrUaH/8AuulIl/bfX3Aw2RGueMCU+zzODaiczLzTZf6yfQLJ7Wp
    EW6/dbcELfJ1ztckk0gkJxVCH9nosqkAxPOSdKdMgSEY8THB3aznzOOLKNh/4GDI
    n/FsBHcnCbaK15xhVnCBP73E+wiixwXpbl/IwoEPzCE4RPvzINfIbvgZgEwK6TNM
    SJziEYtHODTYieEY3BcDK52gLIf/YciSV0IH4zMCg1pEvSVwQiWQZbb+VYttVEFT
    CZXp9yZAOpPwEYTJArKCBEuAweVTz8nz7VsCAwEAAaNFMEMwDgYDVR0PAQH/BAQD
    AgEGMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFPbzejCqEoFDZJ8a89FV
    rW5D0Hi2MA0GCSqGSIb3DQEBCwUAA4ICAQBxhFChA9kb7gjFZTUZlwJ4/F6pmJxm
    bJzc/NTM6YvBH9Qq56V5AOJqQebBLyQk2ZH/U8BjCKEUlT7eCDh0oml1xuZ8RaBa
    fSmjHwW23GwmGAup5ZDvgFXaLdB0Dtq6x8amWHLhQbooUVWiUzX17JYyHShDH4/+
    bondBBjcwdXtJhS9bxNfKwdu90wuL5PDsjqYkZ4R6Us1MV/ein5r+8S6VtK5Aroc
    gwwX1HR5mEEmEy7UiHBPTYIomgl3BVaFfjqRI/KWjZ4fv61G+umX3dIengnf+MV/
    8TWt6PBxocSnRVNiJzCABsMaU4BDfxBFrtM5FWem/sPzFgqb2p7xTo5GMiPlc6xQ
    vbHd0oNy21J8opfxWTsZ0x36wSG4tGPyL9RdG8XGHQOUMYT3dQ4TYFpUrYe4gf33
    QrSs0pf4xNhHlt4o3Of2/V2olkyBj2iDvm08roVe02Nw5Yc3XDLdIEpqiKtkyfTD
    PMzuulM+QJ5kygUry7gve2YKhqsGRwLQWPu3bsq8NLt96m+CF1WPLBR/8mTyJK0b
    p5/QraUKoAq8om8jiUKMSTImLFMxXU+rBuruHfmF4Nc/2AJbIY6pr2VA3hrhc2iT
    EvtKAgfc9AM1J5uzz6+e0nQEa9VgnkGN5uEQdX9jg4ktmEmtxkF4DXAhoVsZ9zcX
    EG8Kw7o0saf2XQ==
    -----END CERTIFICATE-----
- type: replace
  path: /properties/consul/server_cert
  value: |+
    -----BEGIN CERTIFICATE-----
    MIIEMDCCAhigAwIBAgIRAM8aKH5q4yrDTvaYKkFhDAgwDQYJKoZIhvcNAQELBQAw
    EzERMA8GA1UEAxMIY29uc3VsQ0EwHhcNMTcwODA4MTMwODIzWhcNMTkwODA4MTMw
    ODIzWjAhMR8wHQYDVQQDExZzZXJ2ZXIuZGMxLmNmLmludGVybmFsMIIBIjANBgkq
    hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz0bYMoK4z5y/HPSy1tvuMFqt9OHaJrTr
    GzObp8X8h81lunepNoU7GwUEcqmSf1wzvT+X9inGE7Y1U6EzuOadnBWnhJD5l4PI
    ua37Vu1YoLmm2kfFm8l+VFy2YsxXi+AZqWBqor9aHoX3uBmaJWTajxoNSj616CGF
    qv/2/jkmv/jGNCSe0UebSbr9/vO0+m63vjQ+imdeS/QxqXa8ZsenkNDwRhMfJkxe
    mBeu/MglCCfcNo0Dn5mYniYkgAidAv/6Zy2+CLoWZBTtwYwHUFCB9rheGah6HGWh
    /ark4xTC+CmP293tJb/ImIDSPwyDbrEQvVe4t+Cca1bh/eXU6zQQkQIDAQABo3Ew
    bzAOBgNVHQ8BAf8EBAMCA7gwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC
    MB0GA1UdDgQWBBQMs9dgmG1RhJjj2L/fU2Rq0Nmy8jAfBgNVHSMEGDAWgBT283ow
    qhKBQ2SfGvPRVa1uQ9B4tjANBgkqhkiG9w0BAQsFAAOCAgEAgR+t1OTcKZZ5llEd
    NLOfFSpt4lJe3P2K197rpnIYsA992u5SED2mjzpG4FqYlv0ucbijtx+QMpLXoXAB
    ci7s9FUtN6YgmpBZfzUfy/iP6wO+YKzxUBaGYDGIZe92Ha3kovxsQAiY9vSOIjE7
    9jQa9bC53TMGMDK2fkjliPNdU9OfyxXh3tQPdJtRuS6BwDzahDbrP+c1KZR2rBGF
    H7YM7OrDFdhfVbs3O7uftxXOY+kgJFm02IaaKNAQuUgOSWoP5Jh0NmR5zyJNOwBB
    KAh+/GgGrh2cHbIXeF2hsbqfyUBkwXpSkYwpSIMJBpR/dVsTrX+X8IXjRY5RDegK
    OYHP4SbtB/D0s6lZZKKiAsfa6tLGAOVBPz/MISoaEfcxEcCJCwtOggE+pgQSCSQ8
    XxYCPm2wz4fblJ2DVB558zQuRaEZXmRPttfWTQ6ZWkZXvT69G7g/iB8dakEVLj52
    3ZsEzFBjAhr6Hfu9lT1qe3+jCEYQV95zyDhytxMYSfNzvTYWHF5bQRvPVM6FV6cP
    RCInaQ1yMSztaREoBVg4aZNdED/HMdAkO4DK4O8F9De2UhAT1LkoM+THIt2VpWPq
    vwx8FsYbxTKT0bQJbZ5CJmwHczNNj5k+WS9ucPIv9/lgBMQIMx2aXz34CvmMRe14
    TfTXlxguPcq4nwOorse7UW49jZ4=
    -----END CERTIFICATE-----
- type: replace
  path: /properties/consul/server_key
  value: |+
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEAz0bYMoK4z5y/HPSy1tvuMFqt9OHaJrTrGzObp8X8h81lunep
    NoU7GwUEcqmSf1wzvT+X9inGE7Y1U6EzuOadnBWnhJD5l4PIua37Vu1YoLmm2kfF
    m8l+VFy2YsxXi+AZqWBqor9aHoX3uBmaJWTajxoNSj616CGFqv/2/jkmv/jGNCSe
    0UebSbr9/vO0+m63vjQ+imdeS/QxqXa8ZsenkNDwRhMfJkxemBeu/MglCCfcNo0D
    n5mYniYkgAidAv/6Zy2+CLoWZBTtwYwHUFCB9rheGah6HGWh/ark4xTC+CmP293t
    Jb/ImIDSPwyDbrEQvVe4t+Cca1bh/eXU6zQQkQIDAQABAoIBABbLPKU5WOeD3kRp
    6GzWXLg2kKC4YYwWIzCnmTt2+1FX1hMOa65SMnDDOXz+hty4n/v0zVpFt8GdLPoY
    ZR61RanPe8+JPdlapa09o8EocrGiGOYyNFnwa5MNawUsYYhBSbElqDRjhJ6MrvQw
    5JGuKJbKD6IViV2Qqilm4puMX2WG3ChlZhvd41BCoyQLYzkaHxBSQ/XQpB4abVYy
    lxW2GE2szCc9Erq9G5jbUL6Q8Hd72UcxtIHNcKsYcSc01Xyn+cRlswnn4gpc6jjv
    l96bgtiW/bXEdiY4FauSofw0HzxJVXlhwPUDx2+ylgMRNC6giK3SkomWY3BQBmKT
    0QzbYBECgYEA/VN6MpF3sotQsA42gXBnRFGztP8HtFkPeOsxGxWKAVOTEILuWX/n
    ahE9ip3HuuGT5w/j156SvLmb3cdttADZD8RPeTBC8TiVPORnSJnEL3deQjKfVrM9
    Q+Rkca0sBw3/nROf9yJ4C9/tDLIOgkk3Kz430A16SLEE5fQEmIx2ib0CgYEA0Xbv
    dTDtz7tToLc2NkHEYZyxQxp3bgivGtSCwHVlE8I6k6OzEgbgDyIeG6MbTYqO9SZF
    TCHrz4xEOE/jvTqmR6cLC6KeSpCX3CI9DFra19b89lRvMXPyoNHCt+DnTC/DzGTh
    s2tLjrRQXPQjOL4n1QCN55glAMLmXdeTLID3rWUCgYBx6b3DS4KFuPvZjyqXXhIx
    uIOU2jF+uaWpfCkiwrbCDfDNtfK0MD3BhmskD/smYBWAC7cq2FWno9chDXKZROBW
    pLIQDtGrYwRI03RWQz7jEUxDfDwGYqckBmncbECmE3dkDNUb7lYJEPKpiM/Zak7y
    lRHH7qeUVHWdafM/HbqYCQKBgAq9Lkmz2H1t/TugKQdfF9JpVi06jiT2DQQzIQD9
    A9Gfg6FOI0ApWhNsjF6eXif7kpi+/Y6Jrq1VY6n/bo2lFCFYTxipnbP09dQzbS3U
    +qNWQmHeslS2vRnBp1oGDdW6HS+9fFTWi2kllXkuix+9oA0rmhrlkgAX/feRtdny
    QsCBAoGATx7jYmPGW6axH6SM+JxRbpAvkONNt0B49j0TXofwGqxPSL/F6jk0/Z7m
    I9gmcDoTpZb8Y2LJUvxGCowDj0uftHjJpllFXADRcbQ0dzqijaMyTeCn5FVpI951
    4A+y9dZUmAN3WhDhl79mlh3ZA06CdLlhOAS8qp0lUzTTtdoGWpw=
    -----END RSA PRIVATE KEY-----
- type: replace
  path: /properties/consul/agent_cert
  value: |+
    -----BEGIN CERTIFICATE-----
    MIIEJTCCAg2gAwIBAgIQP5R0Tit19rI+GKU3I3UR4DANBgkqhkiG9w0BAQsFADAT
    MREwDwYDVQQDEwhjb25zdWxDQTAeFw0xNzA4MDgxMzA4MjNaFw0xOTA4MDgxMzA4
    MjNaMBcxFTATBgNVBAMTDGNvbnN1bCBhZ2VudDCCASIwDQYJKoZIhvcNAQEBBQAD
    ggEPADCCAQoCggEBAKOINjcj23G2r0LfeEncXyfiFh7h7y8x24x1pEGDjN4W3qrF
    dgWhh2spM9ORFUF9tUKaZMPFf3hQeDdb6WiW6fr8FMMdz9X73VcH2uACm+rJDxF5
    0SFDjbSzKuSHWMSmg0+xReXYeT+rGiCWf392uZXOJO2b5wH82IcJApZj4BzADFMu
    K68ElIpnD9ulGaJdZiEaDX2Bx5D7SPQCqO/FQsNH1JBDoqtbI2BormFHt+3p903K
    zrEaU5oB4W+kMsGY8ZUNbuqp+AWbRsdKwuPmBS9UdJ4Ot9O1jrsspUbYgqUm7mEj
    Ec0wmnZqXC0jvV/nYpJn8PYDA3vask7ysWUJ1wUCAwEAAaNxMG8wDgYDVR0PAQH/
    BAQDAgO4MB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAdBgNVHQ4EFgQU
    ufPZ5zGO1s3u8sRUHqfSXasdfeYwHwYDVR0jBBgwFoAU9vN6MKoSgUNknxrz0VWt
    bkPQeLYwDQYJKoZIhvcNAQELBQADggIBAA7cgNq99yusgLmh5D4jiV6Tu2kNP9Ga
    ur92gN8OSHVrwfPh8m+oj/01ogCgzK6qsrSNySz7U/JSVtd6Khiav11UVwlzdHi7
    790Z5uOOO3MdN6er++ekDHED3kiK/jwYRXWMP2LxSyRtep7gM4o+u3JlFM1hsZRd
    68WDvvM9CY3T4vZ7p94XbB/tNOFkplCQjc0LOggK1b0VOAJ8QXWJGVMssNG/D+F3
    15hbEpbO1Tw7vnFKVDKyc8OGsEtwoWxHa/hCb2Vnq//NWJ99zky8qEydEzu8Y3E2
    E+7u4RBtmJilQrV99bGwpU0YDZV7F7CyXThyM/SFMrruY0WXZ8+LivrRhB/EV2J1
    DYlrVYhIVgsY2G5KE6sOLs+X79MbZVzPpS4UG23z14l+58N0rK21pS2Nu1fWX5H6
    PqPkHl58dZ1A891apnp2Ece0nU+YqEI77GaWFULm6VA2Qz4xy+N4sM4Dy4/nzKsL
    wiKKC+58ROOmqscBUrZYSWsxSq+HrHTDw9LgE2RuImR5MSVmArgMDgsm9W3BOV23
    pc6VU2rPsKCm499v9hluNUmKP2mgB9jjzdgQpNaIyIyto7HG06WdgJsS7xXJUxB7
    bdSr515as+QtyCCNvGJXx9+m9DJSXldoMcQVl9ew3TlsP+zF7/76M9b0lTJtCEy6
    M7tYCNzLJPYs
    -----END CERTIFICATE-----
- type: replace
  path: /properties/consul/agent_key
  value: |+
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAo4g2NyPbcbavQt94SdxfJ+IWHuHvLzHbjHWkQYOM3hbeqsV2
    BaGHaykz05EVQX21Qppkw8V/eFB4N1vpaJbp+vwUwx3P1fvdVwfa4AKb6skPEXnR
    IUONtLMq5IdYxKaDT7FF5dh5P6saIJZ/f3a5lc4k7ZvnAfzYhwkClmPgHMAMUy4r
    rwSUimcP26UZol1mIRoNfYHHkPtI9AKo78VCw0fUkEOiq1sjYGiuYUe37en3TcrO
    sRpTmgHhb6QywZjxlQ1u6qn4BZtGx0rC4+YFL1R0ng6307WOuyylRtiCpSbuYSMR
    zTCadmpcLSO9X+dikmfw9gMDe9qyTvKxZQnXBQIDAQABAoIBABoYcF5YMHpy5oDL
    XEydB+o7X8BJ2Xs0f45ob2+s6FvAVoP1wqGfZxaomoaWTkgHIVehf5bl+zNd0/Ex
    j4uLGYddloqURUgmSunKbRj2EZ9jui3VvJOMTh6ZwKx7FKU81RNwfHDzHFYWnbK5
    kVrrvS20mZv5FuHwUTUrMOiCw46SrY+MKMJh94pezpxZKmk//54wf4HYwGVWW/Ut
    4kkhw0N5YbGOvYYhX8wUac2qt0+TxRX7nWSKMLB1UKirO+FDZCuyg8o8HDDf/Yca
    gMgYs91L8I4S9LJPrqNDDaZn3cm/LlSYXT/nK9PEreJI71qWk5qbFE3mfbBW0VFl
    k4modfkCgYEA0x3SAcQXsMwW5yEOB3rXD7u1YiMPNWa+f8nz4RiKuT+AjdkO/hhY
    mthXB/WkrCdEXK3QdAxQl0pU3yt4GSvYZ8JiNQKGL2vwRARS8ys/sN84B4NQQ4x4
    O4VppcbY8tAZkluv4+dL0eAezrbuKVPdlxTBK24jvktq08t9bK7ELAcCgYEAxkyS
    pWy+VSuUChoctPpHHJ8QB2KqhhH8IUAkPLoY/c7dIbrE2IvKhwb2VaNjFVDHd24r
    uACYD/bRQlo0s/xJlb3xZSrGEWzeA8/X2EYy/GKGISuyAAWHbH9/51P/Q2sujQiQ
    8wtWB4YT5WpK4j6D8JJkjvfFIwubvmRZGEbxOZMCgYEAjvP9VTbL9+pqg70tO8Fh
    SQUI0Ff/H2DgE7XTTxOIM+IdEW/uJ/6iWM+vNvONuwin0L3djgcctyUdDTTpENpQ
    ognM6Co6ZHgJbHUlGgWqDgFIdkXjnqnKbDtti1R3aQuilSlCk+b1vzqsgbr6z787
    J+dk2hytVVjKEHoVBvfcXBcCgYEAqF5JwTWEodI/fxhOuYcrq+yOcobe3LkWh7Dr
    U7h7Eb172nC3RFnlGyLZMztoHKgaxJgBfNjcQ+nAIYNv7kZOwFqnRMu9ovv5wejO
    ju6DyfFpi26LUyNeqcvT8LlMKpUt0Eeusv40DG1WJVtLu69y3WefBBjyBGCN22le
    kJNjrAsCgYA3u32b4uskB/8DIcNowmljuaJSwgJcbv4u+bFB74zkMk9kSkDQJb0p
    kwaOyppKcyaBY0W69qINniwz6xP7vjgsMAlL3bePbHIosBIQ1n1QEp2xShBhectH
    ZVEhdL0i958Fk995PZ6mQ52Kjt11xS7ZrMgrmoD3R8aUsW0m/v73rA==
    -----END RSA PRIVATE KEY-----
