jobs:
- name: hm9000_z1
  instances: 1
  networks:
  - name: cf_private
  properties:
    consul:
      agent:
        services:
          hm9000: {}
    metron_agent:
      zone: z1
    route_registrar:
      routes:
      - name: hm9000
        port: 5155
        registration_interval: 20s
        tags:
          component: HM9K
        uris:
        - hm9000.bosh-lite.com
  resource_pool: small_z1
  templates:
  - name: consul_agent
    release: cf
  - name: hm9000
    release: cf
  - name: metron_agent
    release: cf
  - name: route_registrar
    release: cf
  update: {}

properties:
  dea_next:
    heartbeat_interval_in_seconds: 10
