resources:

- name: aws-environments
  type: pool
  source:
    uri: git@github.com:cloudfoundry-incubator/bits-service-ci.git
    branch: metadata
    pool: locks/aws
    private_key: {{github-private-key}}

- name: ci-tasks
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/bits-service-ci.git
    branch: master
    private_key: {{github-private-key}}
    paths: ["scripts/*", "tasks/*"]

- name: bits-service-release
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/bits-service-release.git
    branch: master
    private_key: {{github-private-key}}


# - name: aws-diego-deployment
#   type: bosh-deployment
#   source:
#     target: {{aws-bosh-target}}
#     username: {{aws-bosh-username}}
#     password: {{aws-bosh-password}}
#     deployment: cf2
#
jobs:
- name: Acquire locks on AWS cf2
  plan: [ { put: cf2, resource: aws-environments, params: {acquire: true} } ]

- name: Bits-Service disabled, 1 CC
  serial: true
  plan:
    - { get: cf-release }
    - { get: git-bits-service-release }
    - { get: ci-tasks, trigger: true }
    - { get: aws-environments, passed: ["Acquire locks on AWS cf2"], trigger: true }
    - task: Create CF deployment manifest with Bits-Service disabled, 1 CC
      file: ci-tasks/tasks/update-aws-cf-manifest.yml
      params: &update-aws-cf-manifest-cf2-config
        IAAS: aws
        MANIFEST_STUBS: manifests/cf-aws-network-2.yml manifests/enable-diego-cats.yml ../bits-service-release/templates/s3.yml
        CF_USER: {{aws-cf2-user}}
        CF_PASSWORD: {{aws-cf2-password}}
        CF_DOMAIN: {{aws-cf2-domain}}
        CF_PUBLIC_IP: {{aws-cf2-public-ip}}
        CF_DEPLOYMENT_NAME: cf2
        BITS_DIRECTORY_KEY: {{cf2-s3-blobstore-bucket-name}}
        BITS_AWS_REGION: {{cf2-s3-blobstore-region}}
        AWS_ACCESS_KEY_ID: {{cf2-s3-blobstore-access-key-id}}
        AWS_SECRET_ACCESS_KEY: {{cf2-s3-blobstore-secret-access-key}}
        BLOBSTORE_TYPE: s3
        BOSH_TARGET: {{aws-bosh-target}}
    # - put: aws-diego-deployment
    #   attempts: 2
    #   params: &params-deployment-cf-release-bits-service-release-diego-release
    #    manifest: manifests/manifest.yml
    #    stemcells: []
    #    releases: ["cf-release-tarball/cf-*.tgz", "bits-service-release-tarball/*.tgz"]
    # - task: Run performance tests
    #   file: TODO
  on_failure:
    { put: aws-environments, params: {release: cf2} }

- name: Bits-Service enabled, 1 CC
  serial: true
  plan:
    - { get: aws-environments, passed: ["Bits-Service disabled, 1 CC"], trigger: true }
    - task: Create CF deployment manifest with Bits-Service disabled, 1 CC
      file: git-bits-service-ci/tasks/update-aws-cf-manifest.yml
      params: &update-aws-cf-manifest-cf2-config
        IAAS: aws
        MANIFEST_STUBS: manifests/cf-aws-network-2.yml manifests/enable-diego-cats.yml ../git-bits-service-release/templates/s3.yml
        CF_USER: {{aws-cf2-user}}
        CF_PASSWORD: {{aws-cf2-password}}
        CF_DOMAIN: {{aws-cf2-domain}}
        CF_PUBLIC_IP: {{aws-cf2-public-ip}}
        CF_DEPLOYMENT_NAME: cf2
        BITS_DIRECTORY_KEY: {{cf2-s3-blobstore-bucket-name}}
        BITS_AWS_REGION: {{cf2-s3-blobstore-region}}
        AWS_ACCESS_KEY_ID: {{cf2-s3-blobstore-access-key-id}}
        AWS_SECRET_ACCESS_KEY: {{cf2-s3-blobstore-secret-access-key}}
        BLOBSTORE_TYPE: s3
        BOSH_TARGET: {{aws-bosh-target}}
    # - put: aws-diego-deployment
    #   attempts: 2
    #   params: &params-deployment-cf-release-bits-service-release-diego-release
    #    manifest: manifests/manifest.yml
    #    stemcells: []
    #    releases: ["cf-release-tarball/cf-*.tgz", "bits-service-release-tarball/*.tgz"]
    # - task: Run performance tests
    #   file: TODO
  on_failure:
    { put: aws-environments, params: {release: cf2} }

- name: Release locks on AWS cf2
  serial: true
  plan:
    - { get: aws-environments, passed: ["Bits-Service enabled, 1 CC"], trigger: true }
    - { put: aws-environments, params: {release: cf2} }

    # - task: Create CF deployment manifest with Bits-Service enabled, 1 CC
    # - put: aws-diego-deployment
    # - task: Run performance tests
    # - task: Create CF deployment manifest with Bits-Service disabled, 3 CC
    # - put: aws-diego-deployment
    # - task: Run performance tests
    # - task: Create CF deployment manifest with Bits-Service enabled, 3 CC
    # - put: aws-diego-deployment
    # - task: Run performance tests
