---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: eirini/ibmcloud

inputs:
- name: eirini-ci-resources
- name: bits-ci-resources
- name: eirini-release
- name: state


params:
  IBMCLOUD_ACCOUNT:
  IBMCLOUD_USER:
  IBMCLOUD_PASSWORD:
  COMPONENT:
  CLUSTER_NAME:
  HELM_CHART:

run:
  path: bits-ci-resources/tasks/helm-install/task.sh
