---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
- name: haproxy-config
- name: private-config

run:
  path: haproxy-config/ha-proxy/tasks/update_config.sh
