resources:
- name: cf-smoke-tests
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-smoke-tests.git
- name: cf-deployment-bitsgo
  type: git
  source:
    uri: https://github.com/petergtz/cf-deployment.git
    branch: bitsgo

- name: bits-service-release-bitsgo-tarball
  type: s3
  source:
    access_key_id: {{s3-blobstore-access-key-id}}
    secret_access_key: {{s3-blobstore-secret-access-key}}
    bucket: ci-bits-service-artifacts
    region_name: eu-west-1
    private: false
    regexp: bits-service-release-bitsgo/bits-service-(.*).tgz

- name: git-cf-acceptance-tests
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-acceptance-tests.git
    branch: master

- name: git-deployment-vars
  type: git
  source:
    uri: git@github.com:cloudfoundry/bits-service-private-config.git
    branch: master
    private_key: {{github-private-key}}
    disable_ci_skip: true



jobs:
- name: deploy-cf-in-((bosh_lite_name))
  serial: true
  plan:
  - aggregate:
    - get: 1-click
    - get: ((bosh_lite_name))-cf-deployment-events
      trigger: true
    - get: ((bosh_lite_name))-ready-for-deployment-events
      trigger: true
      passed: [ update-cloud-config-((bosh_lite_name)) ]
    - get: state
    - { get: cf-deployment, resource: cf-deployment-bitsgo}
    - { get: bits-service-release-bitsgo-tarball, trigger: true }
  - task: detect-stemcell
    file: 1-click/tasks/detect-stemcell.yml
  - task: bosh upload-release bits-service
    file: 1-click/tasks/bosh-upload-release.yml
    input_mapping:
      releases: bits-service-release-bitsgo-tarball
    params:
      BOSH_LITE_NAME: ((bosh_lite_name))
      RELEASE_TARBALL: '*.tgz'
  - task: Generate cf deployment manifest
    file: 1-click/tasks/generate-cf-deployment-manifest.yml
    params:
      BOSH_LITE_NAME: ((bosh_lite_name))
      EXTRA_ARGS: >
       -o cf-deployment/operations/experimental/bits-service.yml
       -o cf-deployment/operations/experimental/enable-bits-service-consul.yml
       -o cf-deployment/operations/experimental/bits-service-webdav.yml
  - put: state
    params:
      repository: out-state
      rebase: true
  - aggregate:
    - task: Deploy cf
      file: 1-click/tasks/bosh-deploy.yml
      params:
        BOSH_LITE_NAME: ((bosh_lite_name))
    # TODO: Do we want to keep this here? This task makes the pipline less generally useful.
    - task: Check system_domain DNS
      file: 1-click/tasks/check-dns.yml
      params:
        BOSH_LITE_NAME: ((bosh_lite_name))

- name:  run-cf-smoke-tests-in-((bosh_lite_name))
  serial: true
  plan:
  - aggregate:
    - get: 1-click
    - get: ((bosh_lite_name))-cf-deployment-events
      passed: [ deploy-cf-in-((bosh_lite_name)) ]
      trigger: true
    - get: ((bosh_lite_name))-ready-for-deployment-events
      trigger: true
      passed: [ deploy-cf-in-((bosh_lite_name)) ]
    - get: state
    - get: cf-smoke-tests
    - { get: bits-service-release-bitsgo-tarball, passed: [deploy-cf-in-((bosh_lite_name))], trigger: true }
  - task: Run smoke-tests
    file: 1-click/tasks/run-smoke-tests.yml
    params:
      BOSH_LITE_NAME: ((bosh_lite_name))

- name: Show CF login summary for ((bosh_lite_name))
  plan:
  - aggregate:
    - { get: 1-click }
    - get: state
    - get: ((bosh_lite_name))-cf-deployment-events
      passed: [ deploy-cf-in-((bosh_lite_name)) ]
      trigger: true
    - get: ((bosh_lite_name))-ready-for-deployment-events
      trigger: true
      passed: [ deploy-cf-in-((bosh_lite_name)) ]
  - task: Show Summary
    file: 1-click/tasks/show-cf-summary.yml
    params:
      BOSH_LITE_NAME: ((bosh_lite_name))

- name: Run CATs
  plan:
    - aggregate:
      - { get: git-deployment-vars }
      - { get: git-cf-acceptance-tests, trigger: true }
    - task: Run CATs
      file: ci-tasks/tasks/run-cats.yml
      input_mapping:
        deployment-vars: git-deployment-vars
        acceptance-tests: git-cf-acceptance-tests
      params: &aws-bits-service-disabled-run-cats-params
        BOSH_TARGET: {{aws-bosh-target}}
        BOSH_USERNAME: {{aws-bosh-username}}
        BOSH_PASSWORD: {{aws-bosh-password}}
        DEPLOYMENT_NAME: cf
        ENVIRONMENT_NAME: aws
        CF_DOMAIN: {{aws-cf1-domain}}
        BLUEMIX_USERNAME: {{bluemix_cloudfoundry_username}}
        BLUEMIX_PASSWORD: {{bluemix_cloudfoundry_password}}
        METRICS_API_KEY:  {{ibm_metrics_api_key}}
        BITS_SERVICE_ENABLEMENT: without-bits-service
      on_failure: &inform-pipeline-operator-diego-aws-cats
    - task: inform-pipeline-operator
      file: ci-tasks/tasks/echo.yml
      params:
        MESSAGE: |
          Consider doing a fresh deployment by manually running job
          [manually-delete-cf-diego-aws]
