---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
  - name: cf-deployment
  - name: state
  - name: 1-click
  - name: ci-tasks
outputs:
  - name: out-state

params:
  BOSH_LITE_NAME: unconfigured
  # EXTRA_ARGS are normally operations and variables `-o op1.yml -v var1=value1 ...`
  EXTRA_ARGS:

run:
  path: 1-click/tasks/generate-cf-deployment-manifest.sh
