resource_types:
  - name: bosh-config
    type: docker-image
    source: { repository: dellemcdojo/bosh-config-resource }

resources:
  - name: collectd-boshrelease
    type: git
    source:
      uri: git@github.com:petergtz/collectd-boshrelease.git
      branch: package-mtlj-plugin
      private_key: ((github-private-key))

  - name: ci-tasks
    type: git
    source:
      uri: git@github.com:cloudfoundry-incubator/bits-service-ci.git
      branch: master
      private_key: ((github-private-key))
      paths: ["runtime-config/tasks/*", "runtime-config/templates/*"]

  - name: collectd-release-tarball
    type: s3
    source:
      access_key_id: ((s3-blobstore-access-key-id))
      secret_access_key: ((s3-blobstore-secret-access-key))
      bucket: ci-bits-service-artifacts
      region_name: eu-west-1
      private: false
      regexp: collectd/collectd-(.*).tgz

  - name: bosh-aws-runtime-config
    type: bosh-config
    source:
      target: ((aws-bosh-target))
      username: ((aws-bosh-username))
      password: ((aws-bosh-password))
      type: runtime-config

  - name: bosh-softlayer-runtime-config
    type: bosh-config
    source:
      target: ((softlayer-bosh-target))
      username: ((softlayer-bosh-username))
      password: ((softlayer-bosh-password))
      type: runtime-config

jobs:
- name: Create and upload collectd-boshrelease with MTLJ Plugin
  serial: true
  plan:
  - aggregate:
    - { get: ci-tasks, trigger: true }
    - { get: collectd-boshrelease, trigger: true }
  - task: Build and Upload collectd-boshrelease
    file: ci-tasks/runtime-config/tasks/bosh-create-release.yml
    input_mapping:
      release-repo: collectd-boshrelease
      ci-tasks: ci-tasks
    output_mapping: { release-tarball: release-tarball }
    params: { RELEASE_NAME: collectd }
  - put: collectd-release-tarball
    params: { file: release-tarball/*.tgz }

- name: Update bosh runtime-config to use collectd-boshrelease
  serial: true
  plan:
  - aggregate:
    - { get: ci-tasks, trigger: true }
    - { get: collectd-release-tarball, trigger: true }
  - task: Generate collectd runtime config file (aws)
    file: ci-tasks/runtime-config/tasks/generate-collectd-runtime-config.yml
    input_mapping:
      collectd-version: collectd-release-tarball
      ci-tasks: ci-tasks
    output_mapping: { runtime-config: runtime-config-aws }
    params: &params
      BLUEMIX_USERNAME: ((bluemix_cloudfoundry_username))
      BLUEMIX_PASSWORD: ((bluemix_cloudfoundry_password))
      METRICS_API_KEY: ((ibm_metrics_api_key))
      IAAS: aws
  - task: Generate collectd runtime config file (softlayer)
    file: ci-tasks/runtime-config/tasks/generate-collectd-runtime-config.yml
    input_mapping:
      collectd-version: collectd-release-tarball
      ci-tasks: ci-tasks
    output_mapping: { runtime-config: runtime-config-softlayer }
    params:
      <<: *params
      IAAS: softlayer
  - aggregate:
    - put: bosh-aws-runtime-config
      params:
        manifest: runtime-config-aws/runtime-config.yml
        releases: [ collectd-release-tarball/*.tgz ]
    - put: bosh-softlayer-runtime-config
      params:
        manifest: runtime-config-softlayer/runtime-config.yml
        releases: [ collectd-release-tarball/*.tgz ]
