#!/usr/bin/env ruby
require_relative 'diego_cf_compatibility'
require 'open-uri'
require 'optparse'

compatible_release = nil

OptionParser.new do |opts|
  opts.on('--diego', 'Show latest compatible diego version') do |v|
    compatible_release = 'diego-release-version'
  end

  opts.on('--garden', 'Show latest compatible garden-runc version') do |v|
    compatible_release = 'garden-runc-release-version'
  end

  opts.on('--cflinux', 'Show latest compatible cflinuxfs2-rootfs version') do |v|
    compatible_release = 'cflinuxfs2-release-version'
  end
end.parse!

if 0 == ARGV.size
  warn "Error - Missing argument: CF_RELEASE_SHA"
  exit 1
end

if nil == compatible_release
  warn "Error - Missing option"
  exit 2
end

github = open('https://raw.githubusercontent.com/cloudfoundry/diego-cf-compatibility/master/compatibility-v10.csv')
compatibility = Compatibility.from(github)

compatible_releases = compatibility.with_cf_release(ARGV.first)

if compatible_releases.empty?
  latest = compatibility.latest_cf_release
  warn "Warning - no compatibility found for this cf-release; using latest (#{latest['cf-release-commit-sha']})."
  compatible_releases = [latest]
end

puts compatible_releases.map { |release| release[compatible_release]}.uniq.sort.last
