properties:
  cc:
    bits_service:
      enabled: true
      public_endpoint: (( concat "http://bits-service." properties.system_domain ))
      private_endpoint: http://bits-service.service.cf.internal
