---
resources:
  - name: haproxy-config
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bits-service-ci.git
      branch: master
      paths:
      - ha-proxy/

  - name: private-config
    type: git
    source:
      uri: git@github.com:cloudfoundry/bits-service-private-config.git
      branch: master
      private_key: ((github-private-key))
      disable_ci_skip: true

jobs:
- name: update haproxy
  plan:
  - { get: haproxy-config , trigger: true }
  - { get: private-config }
  - task: do update
    file: haproxy-config/ha-proxy/tasks/update_config.yml
